# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

production:
  adapter: postgresql
  encoding: unicode
  database: talisman-development
  pool: 5
  username: brian
  password:

development:
  adapter: postgresql
  encoding: unicode
  database: talisman-development
  pool: 5
  username: brian
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: talisman-test
  pool: 5
  username: brian
  password:

